### ISSUE TITLE
Means of rm and od

### ISSUE THREAD

**Issue by ginlock** [yuweihao/KERN#7]
Thank you for your excellent codes. 
I want to know what exact meaning of rm and od. Such as 
return Result(
            od_obj_dists=od_obj_dists,
            rm_obj_dists=obj_dists,
            obj_scores=nms_scores,
            obj_preds=nms_preds,
            obj_fmap=obj_fmap,
            od_box_deltas=od_box_deltas,
            rm_box_deltas=box_deltas,
            od_box_targets=bbox_targets,
            rm_box_targets=bbox_targets,
            od_box_priors=od_box_priors,
            rm_box_priors=box_priors,
            boxes_assigned=nms_boxes_assign,
            boxes_all=nms_boxes,
            od_obj_labels=obj_labels,
            rm_obj_labels=rm_obj_labels,
            rpn_scores=rpn_scores,
            rpn_box_deltas=rpn_box_deltas,
            rel_labels=rel_labels,
            im_inds=im_inds,
            fmap=fmap if return_fmap else None,
        )
in lib object_detector.py.
What's more, why I always get ''RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58'', though I had change batch_size and num_workers to 1 and mine gpu has 16G memory space.
Waiting for your reply,thank you once again.

**Comment by yuweihao** [comment]
Hi @ginlock , thanks for noticing our work! Actually, our code is based on the wonderful repo [neural-motifs](https://github.com/rowanz/neural-motifs) (The code of their repo is really nice!). This part of code is from their repo and I also don't know the exact meaning of rm and od. Maybe I guess "rm" means "removed" and "od" means "old? 

As for second question, did you get this error in which phase? training detector or predcls or sgcls or sgdet or testing phase? We only test our code in this Anaconda environment ```conda install pytorch=0.3.0 torchvision=0.2.0 cuda90 -c pytorch``` on Nvidia TITAN X (Pascal) GPU with 12 G memory. It is better to install the same Anaconda environment. We don't have 16 G memory, so it is sorry that we couldn't come up with a solution. Maybe you could post your exact type of GPU and perhaps other people also encounter the same error so that you could discuss with them.

**Comment by ystluffy** [comment]
"od" means "object detector"
"rm" means "relation model"

**Comment by ginlock** [comment]
thank you for your kindness.
